# Generated by Django 6.0.5 on 2026-05-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
